---
title: "Sweet Time Berlin - Round Cake Quote"
author: "Iwona Helms"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(cakeR)
library(tidyr)
library(stringr)
library(knitr)
library(tibble)
library(kableExtra)

vol <- pi * (d/2)^2 * h
surf_area <- (2 * pi * (d/2) * h) + (2 * pi * (d/2)^2)

i <- cake[[1]]
fill <- cake[[2]]
fon <- cake[[3]]


```

## Cake details: 

* Cake dimensions: `r d` x `r h` inches

* Cake type: `r str_to_title(type)`

* Filling type: `r str_to_title(filling)`

* Fondant type: `r str_to_title(fondant)`

* Board: `r paste(str_to_title(board$board_color),', ',board$board_type,', ',board$size_inches,' inches',sep='')`

* Box: `r box$size`

* Labor: `r paste(deco_minutes,'minutes')`

## Cake Price:

```{r price,message=FALSE,echo=FALSE,warning=FALSE}

iprice <- sum(i$price)
fillprice <- sum(fill$price[-1])
fonprice <- fon[1,]$price
boardprice <- round(board$price_per_unit,digits=2)
boxprice <- round(box$unit_price,digits=2)
lb <- round(work,digits=2)

sub_total <- iprice + fillprice + fonprice + boardprice + boxprice + lb

profit <- round(sub_total * .2,digits=2)

total <- sub_total + profit

cake_name <- paste(str_to_title(gsub('_',' ',type)),' cake',sep='')
fill_name <- paste(str_to_title(gsub('_',' ',filling)),' filling',sep='')
fon_name <- paste(str_to_title(fondant),' fondant',sep='')

prices <- tibble(Category = c(cake_name,fill_name,fon_name,'Board','Box','Labor', 'Sub-Total','Margin','Total Price'),
                 Price = c(iprice,fillprice,fonprice,boardprice,boxprice,lb,sub_total,profit,total))

kable(prices,'html') %>%
  kable_styling(full_width=T) %>%
  row_spec(7,bold=T,color='white',background='grey') %>%
  row_spec(9,bold=T,color='white',background='black')
```

## Cake Ingredients

```{r ingredients,message=FALSE,echo=FALSE,warning=FALSE}

kable(i) %>%
  kable_styling(full_width=T)
```

## Filling Ingredients

```{r filling,message=FALSE,echo=FALSE,warning=FALSE}

fill <- fill %>%
  arrange(price)

kable(fill,'html') %>%
  kable_styling(full_width=T) %>%
  row_spec(3,bold=T,color='white',background='black')
```

## Fondant

```{r fondant,message=FALSE,echo=FALSE,warning=FALSE}

kable(fon)
```
